from __future__ import annotations

from collections.abc import Iterable

from torch import Tensor, device

class Module:
    def parameters(self: Module) -> Iterable[Tensor]: ...
    def state_dict(self: Module) -> dict[str, Tensor]: ...
    def train(self: Module) -> None: ...
    def eval(self: Module) -> None: ...
    def to(self: Module, device: device) -> Module: ...
