from __future__ import annotations

from collections.abc import Iterable, Sequence
from contextlib import AbstractContextManager

import torch.nn as nn  # noqa: F401

# Re-exports for modules/functions used in code
from .serialization import load, save  # noqa: F401

class DType: ...

class Device:
    def __init__(self: Device, device: str | None = ...) -> None: ...

device = Device

class Tensor:
    # Attributes and methods used by our code/tests
    @property
    def shape(self: Tensor) -> tuple[int, ...]: ...
    def __getitem__(self: Tensor, idx: int) -> Tensor: ...
    def item(self: Tensor) -> float: ...
    def backward(self: Tensor) -> None: ...
    def to(self: Tensor, device: Device) -> Tensor: ...
    def size(self: Tensor, dim: int) -> int: ...
    def unsqueeze(self: Tensor, dim: int) -> Tensor: ...
    def tolist(self: Tensor) -> list[int]: ...

def manual_seed(seed: int) -> None: ...
def no_grad() -> AbstractContextManager[None]: ...
def tensor(
    data: Iterable[int] | Sequence[int] | Iterable[float] | Sequence[float] | float,
    dtype: DType | None = ...,
    requires_grad: bool | None = ...,
) -> Tensor: ...
def set_num_threads(threads: int) -> None: ...
def set_num_interop_threads(threads: int) -> None: ...

# Common dtype values used
long: DType
